declare let NsSqlite: any;
declare let global: any;
declare let db: any;
declare let schemaInstalled: any;
declare const CALL_DB_OPEN = 1;
declare const CALL_DB_CLOSE = 2;
declare const CALL_DB_EXECUTE = 3;
declare function postError(callNumber: number, err: any): void;
declare function postResult(callNumber: number, result: any): void;
declare function openDb(callNumber: number, dbName: string, dbSchema: string[], dbVersion: string): void;
declare function executeSql(callNumber: number, sql: string, bindParams: any): void;
